root | 2024-08-26 23:50:36,542 | ERROR | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\NewProject\Virt\test_12_4.py", line 25, in test_run
    runn = rt.Runner(name=1, speed=8)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\NewProject\Virt\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
root | 2024-08-26 23:50:36,543 | ERROR | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\NewProject\Virt\test_12_4.py", line 14, in test_walk
    runn = rt.Runner(name='Спортсмен № 1', speed=-10)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\NewProject\Virt\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -10
